CREATE DATABASE QuanLyBanHang;

USE QuanLyBanHang;

CREATE TABLE Customer (
cID INT NOT NULL PRIMARY KEY,
cName VARCHAR(50) NOT NULL,
cAge INT NOT NULL
);

CREATE TABLE Orders (
oID INT NOT NULL PRIMARY KEY,
cID INT NOT NULL,
oDate DATETIME NOT NULL,
oTotalPrice FLOAT NOT NULL,
FOREIGN KEY (cID) REFERENCES Customer(cID)
);

CREATE TABLE Product (
pID INT NOT NULL PRIMARY KEY,
pName VARCHAR(50) NOT NULL,
pPrice FLOAT NOT NULL
);

CREATE TABLE OrderDetail (
oID INT NOT NULL,
pID INT NOT NULL,
odQTY INT NOT NULL,
PRIMARY KEY (oID, pID),
FOREIGN KEY (oID) REFERENCES Orders(oID),
FOREIGN KEY (pID) REFERENCES Product(pID)
);