CREATE DATABASE QuanLyBanHang;

USE QuanLyBanHang;

CREATE TABLE Customer (
cID INT PRIMARY KEY,
Name VARCHAR(25),
cAge TINYINT
);

CREATE TABLE Orders (
oID INT PRIMARY KEY,
cID INT,
oDate DATETIME,
oTotalPrice INT,
FOREIGN KEY (cID) REFERENCES Customer(cID)
);

CREATE TABLE Product (
pID INT PRIMARY KEY,
pName VARCHAR(25),
pPrice INT
);

CREATE TABLE OrderDetail (
oID INT NOT NULL,
pID INT NOT NULL,
PRIMARY KEY (oID, pID),
FOREIGN KEY (oID) REFERENCES Orders(oID),
FOREIGN KEY (pID) REFERENCES Product(pID),
odQTY INT
);